name: neows_app
description: "java23 Examensarbete Carl_Sundberg - NeoWs"
publish_to: 'Grit Academy'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.8
  envied: ^0.5.2
  flutter_svg: ^0.22.0
  json_annotation: ^4.4.0
  intl: ^0.18.1
  flutter_inappwebview: ^6.1.5
  path_provider: ^2.1.2
  csv: ^5.0.2
  fl_chart: ^0.66.0
 # three_js: ^0.2.2
  drift: ^2.17fff.0
  drift_flutter: ^0.2.0
  path: ^1.9.0
  sqlite3_flutter_libs: ^0.5.24


 # flutter_unity_widget: ^2022.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  envied_generator: ^0.5.2
  drift_dev: ^2.17.0

flutter_icons:
  android: true
  ios: false
  image_path: "lib/assets/images/icon/icon1.png"

flutter:
 uses-material-design: true
 assets:
    - lib/assets/images/icon/icon1.png
    - lib/assets/images/NASA_Worm_logo.svg
    - lib/assets/orbits/
    - lib/assets/astroidReadTest.csv
    - lib/assets/latest_fulldb.csv
    - lib/assets/images/orbit_placeholder.png
    - .env


