name: neows_app
description: "java23 Examensarbete - NeoWs"
publish_to: 'Grit Academy'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.8
  envied: ^1.2.0
  flutter_svg: ^2.2.0
  json_annotation: ^4.4.0
  intl: ^0.20.2
  path_provider: ^2.1.4
  fl_chart: ^1.1.1
  shared_preferences: ^2.3.2
  cached_network_image: ^3.3.1
  timeago: ^3.6.1
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.3
  modal_bottom_sheet: ^3.0.0
  package_info_plus: ^8.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.6.0
  json_serializable: ^6.7.1
  envied_generator: ^1.2.0

flutter:
  uses-material-design: true
  fonts:
    - family: EVA-Matisse_Classic
      fonts:
      - asset: lib/assets/fonts/EVA-Matisse/EVA-Matisse_Classic.ttf
    - family: EVA-Matisse_Standard
      fonts:
      - asset: lib/assets/fonts/EVA-Matisse/EVA-Matisse_Standard.ttf

  assets:
    - lib/assets/images/icon/icon1.png
    - lib/assets/images/orbit_placeholder.png
    - .env

